<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>false</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>3xgcafe-Guard</AssemblyName>
    <RootNamespace>ScreenGuard</RootNamespace>
    <Company>3xgcafe</Company>
    <Product>3xgcafe Guard</Product>
    <Description>3xgcafe 系列 · 空闲自动锁定屏幕</Description>
    <Version>2.0.0</Version>
    <FileVersion>2.0.0</FileVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <TieredCompilation>true</TieredCompilation>
    <TieredPGO>true</TieredPGO>
    <RetainVM>false</RetainVM>
    <ThreadPoolMinThreads>1</ThreadPoolMinThreads>
    <ThreadPoolMaxThreads>16</ThreadPoolMaxThreads>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.2" />
  </ItemGroup>

</Project>
